{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "react-directory-client-side-solution",
    "id": "00000000-0000-0000-0000-000000000000",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "features": [
      {
        "title": "react-directory Feature",
        "description": "Activates elements of the react-directory solution.",
        "id": "11111111-1111-1111-1111-111111111111",
        "version": "1.0.0.0"
      }
    ],
    "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read.All"
      }
    ]
  },
  "paths": {
    "zippedPackage": "solution/react-directory.sppkg"
  }
}
