name: Build SPFx (react-directory)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify sample folder exists
        run: |
          ls -la
          ls -la samples/react-directory

      - name: Use Node 18.x (SPFx 1.18+)
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'

      - name: Install
        working-directory: samples/react-directory
        run: |
          npm config set legacy-peer-deps true
          npm install --no-audit --no-fund

      # Gulp writes ESLint warnings to stderr in CI and sets a non-zero exit.
      # We allow the step to continue because the bundle completed successfully.
      - name: Build (allow warnings)
        working-directory: samples/react-directory
        run: |
          npx gulp bundle --ship || echo "Ignoring non-zero exit due to warnings"

      - name: Package
        working-directory: samples/react-directory
        run: npx gulp package-solution --ship

      - name: Show output folder (for sanity)
        run: ls -la samples/react-directory/sharepoint/solution

      - name: Upload .sppkg
        uses: actions/upload-artifact@v4
        with:
          name: sharepoint-solution
          path: samples/react-directory/sharepoint/solution/*.sppkg
